version: 2
updates:
  # Mises à jour des dépendances Python (pip)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "04:00"
    open-pull-requests-limit: 10

  # Mises à jour des GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
