name: Generate SBOM CycloneDX

on:
  push:
    branches: [ "main" ]

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Generate the SBOM CycloneDX
        uses: anchore/sbom-action@v0
        with:
          format: 'cyclonedx-json' # Or 'cyclonedx-xml'
          output-file: 'bom.cyclonedx.json'

      - name: Archive the SBOM as an artefact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-cyclonedx
          path: bom.cyclonedx.json
